### ISSUE TITLE
Can't find the options page

### ISSUE THREAD

**Issue by jschwartzenberg** [iriiiina/JIRA-Issue-Opener-FF#12]
I just installed version 3.1 of the extension in Firefox 45.6.0 (RHEL 7 version), but I can't find the options page to set the URL.

There's no preferences button for this extension in the list like there is for the others. How can I access this options page?

**Comment by iriiiina** [comment]
Sorry for the late answer. This extension is compatible with latest FF versions 50.* and is not compatible with ESR 45.x. I will update this information in Addon Store during next version update, sorry for disinformation.

**Comment by jschwartzenberg** [comment]
Thanks for the reply. I just checked. It seems that version 52 will become an ESR and it is planned to be released in June. So by that time ESR should be supported as well, but that will take some time.
Is there an older version that could already work with the current ESR?
